### ISSUE TITLE
resizevolume doesn't resize partition

### ISSUE THREAD

**Issue by jbheman** [jtriley/StarCluster#100]
hi-
i've tried twice now to resize my ebs-volume. the size listed on 'starcluster listvolumes' and ec2's list of volumes reflects the increase. However, when I run df -h the device appears to be the same size.. looking into resize2fs -p /dev/... now. There is only one partition on this disk and i mount it as /home. Also, when i run frisk -l on this newly resized volume it says:

---

Disk /dev/xvdz: 75.2 GB, 75161927680 bytes
255 heads, 63 sectors/track, 9137 cylinders, total 146800640 sectors
Units = sectors of 1 \* 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x00000000
## Disk /dev/xvdz doesn't contain a valid partition table <- problem seems to be related to this

On a related note: there is some confusion between ec2 and starcluster on mount points. ec2 mounts on /dev/sd\* and i believe linux translates those to /dev/xvd_. However in some cases the /dev/sd_ names get into /etc/fstab..

best, jason

**Comment by jtriley** [comment]
Hmmm I'm repartitioning already using sfdisk. Perhaps I need to delete the partition before repartitioning and resizing. I'll experiment with this today and see if I can reproduce/fix this.

Concerning /dev/sd\* names getting into /etc/fstab: this should only happen if the device actually shows up as /dev/sd\* rather than /dev/xvd_. StarCluster first checks /dev/sd_ then /dev/xvd\* and uses whichever exists. If you can give me a list of steps to reproduce this issue that'd be extremely helpful.

**Comment by jbheman** [comment]
btw, thanks a million for developing this most useful tool.

re: /dev/sd\* : i've had to derive my own ami, which is now fairly stable, but if i come across the issue again i'll send you the code.

it might be worthwhile to create some sort of 'plugin exchange' where people can share and buildup a repo.

best, jason

**Comment by jtriley** [comment]
I think I've got this figured out but just to confirm could you paste the
output of 'fdisk -l' for the original disk you're trying to resize? Thanks!
