### ISSUE TITLE
Cluster receipts

### ISSUE THREAD

**Issue by nmichaud** [jtriley/StarCluster#114]
Instead of using pickle, it might be more forward compatible to save all necessary attributes into a json or yaml object, especially since the all the important attributes are basic variable types (I have to check more carefully, but it seems that no objects are stored in the pickle).

**Comment by jtriley** [comment]
Switched to using JSON instead of pickle to store the settings and also moved them from the security group description field to security group tags (and some to master's userdata), however, we still must compress and b64 encode the JSON tags given that there's a maximum of 10 tags allowed and each tag has a 255 char limit.
