### ISSUE TITLE
Eucalyptus Interface

### ISSUE THREAD

**Issue by Soulou** [jtriley/StarCluster#116]
Hi,

I wish to interface StarCluster with my Eucalyptus infrastructure. (which use the same API as AWS of course)

I add 'AWS_REGION_NAME' and 'AWS_REGION_HOST' in my config file to fit with my setup. And to manage the endpoint (which is /services/Eucalyptus) I add the AWS_EC2_PATH=/services/Eucalyptus and AWS_S3_PATH=/services/Walrus

But it doesn't work well. Does anyone has already done that ?

Thank you
## 

Soulou

**Comment by Soulou** [comment]
Some details about my issue :

```
!!! ERROR - None: Failure: 400 Bad Request
Failed to bind the following fields:
Filter.1.Name = group-name
Filter.1.Value.1 = @sc-newcluster

```

Config file : 

https://gist.github.com/e7e409b40f937f61390e

**Comment by jtriley** [comment]
@Soulou the current version is not compatible with Eucalyptus given that Eucalyptus does not support a recent AWS API that includes tagging and filtering. I'd love to support Eucalyptus but this currently would require sub-classing and re-implementing several core pieces of code that I simply don't have the time for at this point. If you're interested in doing this I'd be happy to point you in the right direction and would be willing to accept a pull request that implements this...

**Comment by jziniti** [comment]
@jtriley My apologies for a late post on a closed issue, but I would like to take a closer look at this issue to see if it is something I could implement for our group.  Could you give me some pointers on where I should be looking in the code? Thanks, JZ.

**Comment by jtriley** [comment]
@jziniti My apologies for the delay. Basically anywhere that filters have been used in the code will need to be downgraded to fetching _all_ entries and manually performing the filters locally when using Eucalyptus/OpenStack. This is slow in general and _really_ slow for big clusters which is the main reason I switched to using them in addition to the fact that they require less code to be written/maintained given that the filtering occurs server-side.

Tags are mostly used by StarCluster to store cluster metadata and are applied to the cluster's security group. You could modify the Cluster.load_receipt() code to not use tags at all and instead update the create_node code to write this data into the master node's userdata. The reason I'm using tags and not storing everything in userdata by default is because of performance and ease of use.

**Comment by ro6ert** [comment]
@jtriley It seems that most of the requests for information from the server go though boto's connection.py. The filter values are propagated from the calling functions in starcluster to connection.py in boto. We have written code to manually filter the xml returned by eucalyptus at the boto level and strip it of the "euca:" namespace prefixes so that the returned xml closely resembles the xml returned by aws. Do you think there are any problems with this approach?

**Comment by worldveil** [comment]
I'm curious, does StarCluster now support or plan to support Eucalyptus / OpenStack?

**Comment by ro6ert** [comment]
Eucalyptus is now very close to the Amazon API. We have a fork that works
with Eucalyptus. Special care must be taken to handle user data and other
details.

**Comment by worldveil** [comment]
With EBS as well? 

Great, where might I find this fork?

**Comment by ro6ert** [comment]
Hello Worldveil,

Could you please contact me at rerpc at channing dot harvard dot edu to
discuss the Eucalyptus capable boto-starcluster forks?

-Rob
