### ISSUE TITLE
listcluster command blows up when a cluster is being created

### ISSUE THREAD

**Issue by bmabey** [jtriley/StarCluster#14]
When trying to bring up a large cluster I almost always have certain nodes that never come up or they do come up but never respond to SSH.  What than means is that Starcluster will wait indefinelty for the stragler while the other nodes sit idle:

```
>>> Waiting for SSH to come up on all nodes...
39/40 |\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\   |  97%   
```

I know you are aware of this, and so I'm not reporting this.  I'm reporting the fact that when I try to list my clusters when in this state it blows up.  This is the error I get:

```
$ starcluster listclusters
StarCluster - (http://web.mit.edu/starcluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

cli.py:156 - ERROR - failed to load cluster receipt: Incorrect padding
```

I would like to be able to list the clusters and know which nodes are running and which ones are not so I can kill/restart the running nodes that are not responding to SSH, and/or resize my cluster.  Right now my only way of finding the strangler node is to manually check each instance by trying to ssh into them.

**Comment by jtriley** [comment]
The error you get is because of old security groups/clusters that were either started with the current stable version or an earlier commit of the development code. The format i'm using to store cluster meta-data and node aliases has changed a bit in the github code which causes this error...sorry for this.

The easiest way to fix this error is to shutdown your current running clusters at your convenience and then remove all security groups that start with '@sc-' in the Amazon Web Console (http://aws.amazon.com/console)

Concerning the ability to know which nodes have ssh running or not I'm going to add an option to the listclusters command that will output whether SSH is up or not on each node using the same check that the "start" command uses. It will look _something_ like this:

$ starcluster listclusters --ssh-status

....
master i-asdf0232 ec2-asdf-asf.aws.com (SSH: Up)
node001 i-basd222 ec2-fdsa-asf.aws.com (SSH: Down)
....

In the meantime when you have stragglers try rebooting the entire cluster using the 'restart' command. This command reboots all nodes and reconfigures the cluster. This would likely fix the stragglers in most cases.

I'm going to close this bug and then open a new one for this new option to listclusters.
