### ISSUE TITLE
ImprotError: No module named boto.exception

### ISSUE THREAD

**Issue by simonkahan** [jtriley/StarCluster#140]
An issue raised by three users but not addressed on Amazon's AWS forum  ( https://forums.aws.amazon.com/thread.jspa?threadID=81617 ) is this python ImportError -- I get it when running on my macbook 10.6.8 system, though not on our linux install.  (is it something to do with python path settings?)
Anyone know what to do to alleviate it?  Thanks!

bash-3.2$ bin/starcluster start smallcluster
Traceback (most recent call last):
File "bin/starcluster", line 2, in <module>
from starcluster import cli
File "/Users/skahan/StarCluster/starcluster/cli.py", line 14, in <module>
from boto.exception import BotoServerError, EC2ResponseError, S3ResponseError
ImportError: No module named boto.exception
bash-3.2$

**Comment by jtriley** [comment]
@simonkahan Would you mind trying the latest 0.93.3 version? You should be able to install this on Ubuntu with a single command:

```
$ sudo easy_install StarCluster
```

This will download and install the latest version as well as the latest dependencies (including boto). Let me know if that solves it.

**Comment by jtriley** [comment]
Just responded to the AWS thread but here's the post for others:

I'm not sure if you installed StarCluster manually (using setup.py) or using easy_install but my guess is that you did a manual install without having setuptools installed which is why the proper dependencies were not downloaded and installed automatically (e.g. boto).

Most distributions have a setuptools package that you can install to solve this. For Ubuntu:

```
$ sudo apt-get install python-setuptools
```

If your distribution does not have such a package you can easily install it by unpacking StarCluster, changing to the StarCluster folder and running:

```
$ sudo python distribute_setup.py
```

This will download and install the latest setuptools in your current python installation.

After installing setuptools you can either try manually installing again by running "sudo python setup.py install" again or just use the easy_install command (recommended):

```
$ sudo easy_install StarCluster
```

This will then properly download and install StarCluster and all of its dependencies.

**Comment by jtriley** [comment]
I'm closing this issue for now given that I'm fairly confident you did not have setuptools when installing. Please reopen If installing setuptools and then reinstalling StarCluster using easy_install as mentioned above doesn't fix things for you.

**Comment by simonkahan** [comment]
The problem seemed to be in _how_ it was installed.  Port installed it, but
apparently not well enough.  I had to download directly, and then each
dependence in turn.  After several more downloads I was able to get
starcluster to work.
Thanks!

**Comment by pmehra7** [comment]
Still getting an error even after using easy_install and pip installs. I was able to launch one cluster on AWS then terminate it. Following this I get the following error even after reinstalling starcluster:

Traceback (most recent call last):
  File "/usr/local/bin/starcluster", line 9, in <module>
    load_entry_point('StarCluster==0.95.6', 'console_scripts', 'starcluster')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/cli.py", line 30, in <module>
    from boto.exception import BotoServerError, EC2ResponseError, S3ResponseError
ImportError: No module named exception

I am able to import boto in python shell
