### ISSUE TITLE
Development version Exception in Thread-22

### ISSUE THREAD

**Issue by jstjohn** [jtriley/StarCluster#152]
After starting a cluster I get this message, not sure if it means anything:

```
You can activate a 'stopped' cluster by passing the -x
option to the 'start' command:

    $ starcluster start -x smalltest

This will start all 'stopped' nodes and reconfigure the
cluster.
Exception in thread Thread-22 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 551, in __bootstrap_inner
```

**Comment by jtriley** [comment]
This is a bug in the Python 'ssh' library that should now be fixed in the new version of paramiko (ssh migrated back to paramiko). I'm planning on updating the ssh dependencies for StarCluster to the latest paramiko version before release which should hopefully fix this error. WIth that said, this error, albeit annoying, is completely harmless and occurs when the StarCluster application is exiting.
