### ISSUE TITLE
starcluster ebsimage fails on cc1.4xlarge hvm image

### ISSUE THREAD

**Issue by jstjohn** [jtriley/StarCluster#155]
> > > Removing private data...
> > > Creating EBS image...
> > > Waiting for AMI ami-6e77cf07 to become available...!!! ERROR - Error occurred while creating image
> > > !!! ERROR - Unhandled exception occured
> > > Traceback (most recent call last):
> > >   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/cli.py", line 255, in main
> > >     sc.execute(args)
> > >   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/commands/ebsimage.py", line 69, in execute
> > >     *_self.specified_options_dict)
> > >   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/awsutils.py", line 768, in create_ebs_image
> > >     return icreator.create_image(size=root_vol_size)
> > >   File "<string>", line 2, in create_image
> > >   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/utils.py", line 91, in wrap_f
> > >     res = func(_arg, **kargs)
> > >   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/image.py", line 211, in create_image
> > >     return self._create_image_from_ebs(size)
> > >   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/image.py", line 231, in _create_image_from_ebs
> > >     snap = img.block_device_mapping['/dev/sda1'].snapshot_id
> > > KeyError: '/dev/sda1'

This is with the starcluster public ami:
ami-4583572c

**Comment by jtriley** [comment]
@jstjohn Interesting, I'll give it a shot and see what's up. In the mean time if you still have ami-6e77cf07 I'd be interested to see the output of:

```
$ starcluster shell
[1]> img = ec2.get_image('ami-6e77cf07')
[2]> print img.block_device_mapping
```

**Comment by JohnCEarls** [comment]
In [1]: img = ec2.get_image('ami-580e8768')

In [2]: print img.block_device_mapping
{u'/dev/sde1': <boto.ec2.blockdevicemapping.BlockDeviceType object at 0x3870590>, u'/dev/sdb1': <boto.ec2.blockdevicemapping.BlockDeviceType object at 0x3870cd0>, u'/dev/sda1': <boto.ec2.blockdevicemapping.BlockDeviceType object at 0x38727d0>, u'/dev/sdd1': <boto.ec2.blockdevicemapping.BlockDeviceType object at 0x3870d10>, u'/dev/sdc1': <boto.ec2.blockdevicemapping.BlockDeviceType object at 0x3870c50>}

I have the same error, on any instance type, this is the output of above command.

Does make the AMI, and it appears to work fine.  Been having this issue for a while, but since it still made the ami, I never thought it was a big enough deal to post about.

I am using the latest dev, with experimental features on.  Ubuntu 10, python 2.6.5.

**Comment by jtriley** [comment]
@JohnCEarls Awesome, thanks for the info. Looks like this might be an issue where the full block_device_mapping is not returned from AWS in the response from the create_image call. The code likely needs to be updated to first wait for the proper block device mapping to show up (ie /dev/sda1)  and _then_ wait for the snapshot.

**Comment by jtriley** [comment]
FYI this can be achieved simply by refetching the AMI using DescribeImages until the block device mapping shows up. I will likely set this to timeout and error after 5 fetches...

**Comment by JohnCEarls** [comment]
Cool beans.  Thanks!
