### ISSUE TITLE
Can't pickle plugin sge while load balancing

### ISSUE THREAD

**Issue by FinchPowers** [jtriley/StarCluster#165]
Case: With the load balancer, adding a first node is fine. Adding a second one gives pickle errors.

**Comment by FinchPowers** [comment]
Fix in progress https://github.com/datacratic/StarCluster/tree/165_loadbalance_sge_pickling
Testing pending.

**Comment by jtriley** [comment]
@FinchPowers Good catch, thanks for reporting! However, this should be fixed within the Cluster class and not on a per-plugin basis. This is due to a recent change where the plugins kwarg is now a list of plugin objects instead of a list of dicts from the config. This helps to decouple Cluster and StarClusterConfig. Fortunately I have a simple fix for this coming.
