### ISSUE TITLE
getpwnam for getting cluster user's UID and GID?

### ISSUE THREAD

**Issue by derkuci** [jtriley/StarCluster#196]
Currently in clustersetup.py, the UID and GID of a "new" user is obtained by looking at the user's home directory, and later the UID and GID are used to create that new user on cluster nodes.  However, a user may exist on master without a home directory (e.g., sgeadmin on Fedora with gridengine RPMs) or its home directory may live somewhere other than /home.  Is it better to use getpwnam, like the patch below does?

``` patch
diff --git a/starcluster/clustersetup.py b/starcluster/clustersetup.py
--- a/starcluster/clustersetup.py
+++ b/starcluster/clustersetup.py
@@ -137,15 +137,10 @@
         and GID for a new user.
         """
         user = user or self._user
-        home_folder = '/home/%s' % user
-        mconn = self._master.ssh
-        if mconn.path_exists(home_folder):
-            # get /home/user's owner/group uid and create
-            # user with that uid/gid
-            s = mconn.stat(home_folder)
-            uid = s.st_uid
-            gid = s.st_gid
-        else:
+        try:
+            s = self._master.getpwnam(user)
+            uid, gid = s.pw_uid, s.pw_gid
+        except KeyError:
             # get highest uid/gid of dirs in /home/*,
             # increment by 1 and create user with that uid/gid
             uid, gid = self._get_max_unused_user_id()
```

**Comment by jtriley** [comment]
@derkuci Your patch assumes the user already exists, however, at this point the user has yet to be created so getpwnam is not useful in this context.

The existing code tries to be 'smart' about how it creates the user by paying attention to whether the user's `$HOME` directory exists (in the usual location `/home`) and what UID/GID numbers are assigned to it. Assuming the user's `$HOME` folder in `/home` does exist _before_ the user has been created, StarCluster will create the user with the existing UID/GID on the folder in order to avoid having to chown/chmod potentially many GBs of data to get the permissions right which can take _forever_. This is the case for example if you mount an EBS volume on `/home`.
