### ISSUE TITLE
SGEStats.job_multiply in the sge load balancer can bug out on some array jobs

### ISSUE THREAD

**Issue by scrappythekangaroo** [jtriley/StarCluster#199]
You can sometimes have array jobs that look like '2,4-10:1'.  job_multiply can't handle this since it's expecting either singleton jobs or array jobs that look like '1-10:1'.

Proposed fix is located here;
https://github.com/scrappythekangaroo/StarCluster/commit/44f66fa3fd2edd034cd85038966d223cf74c26a3

I'm not sure that such behaviour will arise in practice with the current load balancer, but it can be brought on after some changes (e.g. after resubmitting jobs that are running on a node that will be shut down).

**Comment by jtriley** [comment]
Thanks for reporting and sorry for the delay. I recently refactored the job_multiply function to _count_tasks when I improved qstat parsing in ee5d62441b0b785fcf689e1c6096b4521c78c959. In this refactor I added support for the case that the 'tasks' output from qstat was a list of ids but not a list of ids AND range specifications mostly because I hadn't come across that output before. In any event, I have a fix coming shortly.
