### ISSUE TITLE
add support for Amazon VPC

### ISSUE THREAD

**Issue by jtriley** [jtriley/StarCluster#21]
Requested by Adam Kraut in the StarCluster mailing list:

http://mailman.mit.edu/pipermail/starcluster/2011-April/000706.html

**Comment by jtriley** [comment]
@ank did you ever try this in your local fork? if you still need it I'll try to add this in or merge your changes...

**Comment by ank** [comment]
@jtriley I ended up not having time so it become lower priority. I imagine it'd be generally useful to have in starcluster and if you needed someone to test or debug I'd be happy to.

**Comment by rayrayson** [comment]
I modified the code and just started a few nodes inside my VPC - however, I still need to create the routing table & gateway (the setup procedure for those should be independent of StarCluster, as most likely it would involve the local IT department) in order to fully test the setup.

**Comment by jtriley** [comment]
@rayrayson That's great, looking forward to the updates. I'll have to read up on Amazon VPC and play around - haven't experimented with it yet. I agree that the routing table, gateway, etc setup should probably be configured independent of StarCluster given that it's fairly involved and probably outside the scope of StarCluster. That being said if there are simple VPC-related things that we can do to make it easier for the majority of users I'm all for it.

**Comment by ank** [comment]
@rayrayson Awesome! This is very high on my wish list. Let me know if you need extra resources for implementation/test/docs.

**Comment by jassinm** [comment]
First thanks for this project : seems like a great alternative to whirr...
any update on the VPC feature request? 
Is there any code i could fork which started to implement this?
otherwise i would give it a shot:
-  add vpcid to config + use boto VPCconnection
-  ability to specify the routing  of the instances via user_data boto in config_file to home / office LAN

ideally at some point one could have the ability to create a vpc with a openvpn/nat server on the fly without specifying an already existing vpc

Thanks

**Comment by rayrayson** [comment]
I wrote some code for VPC support a while ago (ie. last year and tested it early this year), but there are still unsolved issues:

1) Boto bug 1 - Security group issues in VPC:

Without a fix, StarCluster can't authorize() or delete() VPC security groups:

https://github.com/boto/boto/issues/561

I developed some workarounds - but I think the fix should go into Boto as the bug is in Boto. And the Boto maintainers are planning to fix it in the 2.4 release. If they can't fix it due to other technical limitations, then we will consider those (ugly) workarounds...

2) Boto bug 2 - run_instances() should support Placement.Tenancy:

A smaller issue is that there is no support for "dedicated" (single-tenant hardware) support in Boto, which is a VPC feature:

https://github.com/boto/boto/issues/599

Most people are satisfied with non-dedicated, I believe, as this is the only instance tenancy type you get in non-VPC EC2. However, it can be useful to run on dedicated nodes - for example, when you wanted to measure the performance or you don't want other people's workload to affect the performance of your instances.

3) StarCluster + VPC limitation:

StarCluster uses the security group description field to store cluster configuration. However, security groups in VPC are more restrictive and won't let us store "unlimited" amount of information.

We've tried and found that we did not hit any limit on the length of the description field with non-VPC. However, there is a limit of 256 bytes in VPC. So Justin is finding a way to change the location where SC stores the cluster configuration. (Since Justin is working on this issue I will let him comment on it...)

# Status

The first Boto bug will be fixed in the 2.4 Boto release, and the second bug is not a showstopper. I discovered the third issue and at the beginning I tried to use the tags of the security group to store the cluster info. But then I discussed the issue with Justin and he found that it is better to store the configuration in other places (eg. user_data). Technically it is not a big issue as long as there is a place to store the configuration data.

locojay, if you want to work on this can you find an easy way to launch a VPC on demand, or to configure an OpenVPN node for the "Customer Gateway". I am going to follow the instructions in this guide to setup a VPC:

http://openfoo.org/blog/amazon_vpc_with_linux.html

And we will test our code using this gateway in the integration phrase - ie. Boto 2.4, with my VPC code (developed 6 months ago) and Justin's cluster config location change in SC - then we should be able to test the whole thing!

Please let us know what you would like to do on the list, and IMO it is a little nicer than discussions in a bug report.

(BTW, I personally would prefer to configure network settings manually but then other people may want to just run an SC cluster in a VPC.)

Rayson

Open Grid Scheduler / Scalable Grid Engine
http://gridscheduler.sourceforge.net/

**Comment by jassinm** [comment]
justin as mentioned on irc . i cleaned up the push to track the develop branch. you can comment and find it @ https://github.com/locojay/StarCluster/tree/vpcdev

**Comment by steevmi1** [comment]
Is there any update on this issue? Is the vpcdev branch worth testing with to help make this feature ready for prime time?

**Comment by adgaudio** [comment]
Hello @jtriley @locojay,

I think this is would be an awesome feature to have!  I rebased locojay's vpcdev branch against current develop (conflicts manually resolved).  Will be testing it shortly.  @locojay, are you still interested in maintaining this PR?  I'd love to try getting @jtriley to merge it, so if you are still interested in this, let me know! 

@jtriley - do you know of any significant blockers currently that would prevent merging this into starcluster?

fyi - my rebased branch is here:  https://github.com/adgaudio/StarCluster/tree/vpcdev

**Comment by rayrayson** [comment]
@adgaudio - let me know if you want others to do some beta testing. I have never tried locojay's branch before as I always run the latest StarCluster trunk.

Rayson

---

Open Grid Scheduler / Scalable Grid Engine
http://gridscheduler.sourceforge.net/
http://cloud.scalablelogic.com/

**Comment by adgaudio** [comment]
@rayrayson Thanks!  I'm going to check this out in detail now, so l'll let you know as soon as it's ready for some beta testing.

**Comment by adgaudio** [comment]
@rayrayson - I have successfully started and terminated multiple clusters in the vpc today!   If you'd like to try beta testing, you can use the code at the link I re-pasted below.  I'll probably make a few more simple changes to simplify one or two parts, but the existing code is generally very good.

https://github.com/adgaudio/StarCluster/tree/vpcdev

I'm not sure how elastic ip assignment works, so for me (and everyone else?), the requirement for vpc is that you must start clusters from within the vpc.  Otherwise, when starting up a vpc cluster from outside the vpc, the master node must somehow have an externally visible or tunneled ip address.  If spinning up vpc clusters outside the vpc is so important (which doesn't seem very sensible anyways), we can consider designing a 2nd pr after this one.

**Comment by adgaudio** [comment]
A second, and perhaps more significant problem I'm experiencing is that security groups can't be deleted without -f option... perhaps due to some bug in AWS where the nodes are stated as terminated but still somehow connected to the security group.  Specifically, calling 

```
starcluster terminate my_vpc_cluster

        log.info("Removing %s security group" % sg.name)
        self.ec2.conn.delete_security_group(group_id=sg.id)
```

results in the following failure response from Amazon:

```
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
...
<Error>
    <Code>DependencyViolation</Code>
    <Message>resource sg-xxxxxxxx has a dependent object</Message>
</Error>
```

So, what I have to do is follow up with "starcluster terminate -f my_vpc_cluster".  This certainly isn't pretty.

**Comment by adgaudio** [comment]
With help from the ops team at my work, we've determined that the above seems like a bug in Amazon, and that the best approach is to wait several minutes before attempting to delete the security group again.

Also, here is a plugin I'm using to change starcluster security group permissions.  It might be useful for anyone else attempting to use StarCluster in VPC: https://gist.github.com/adgaudio/5208195

**Comment by schmutze** [comment]
Howdy,

Wanted to check in on the status of VPC support.
Is there anything I can do to help? Are there any remaining issues I can help get resolved?

thanks!
chad

**Comment by adgaudio** [comment]
Hi Chad,

Thanks for your interest!  Currently, my pr works in vpc, and I use it
daily to spin up nodes.  There are a couple caveats (mentioned in the pr)
that you (or anyone interested) could certainly fix:
- terminating a cluster will fail to remove the security group on the
  first try.  You have to terminate -f the cluster several seconds or minutes
  later to completely remove the lingering security group.  It would be much
  more convenient to have the terminate command wait until the security group
  is properly deleted.
- ssh to nodes and most usage of starcluster vpc code must happen inside
  your vpc because there is currently no support for spinning up or sshing to
  vpc clusters from outside of the vpc.  Arguably, we might want it this way
  for security reasons, but I'm open to ideas here, and would actually like
  to be able to spin up clusters from outside the vpc.
- I'm not sure if this is already supported, but it would be cool if vpc
  starcluster nodes could have a private dns name that is prefixed with their
  cluster name or any arbitrary string.  For instance, "starcluster start
  mycluster" would create nodes with private dns names of "mycluster-master"
  and "mycluster-node001"
- Consider VPC support when using starcluster plugins generally untested.
  It could be convenient if people who use the vpcdev branch comment on what
  standard plugins do work and which ones don't.

The top item is the most useful, relevant and (probably the) simplest to
fix.  If you're interested in working on any of these topics, I'd love it
if you made a pr to my branch,
https://github.com/adgaudio/StarCluster/tree/vpcdev, rather than to the
default starcluster repo so there's no confusion about which vpc pr is most
up to date.

Thanks for reaching out!

Alex

**Comment by jtriley** [comment]
@adgaudio Thanks for your hard work on the vpc branch and my apologies for not giving feedback much sooner. I'm hoping to begin merging your branch very soon given that Amazon is slowly shifting folks towards VPC it seems.  With that said the default VPC stuff has forced me to deal with a couple (not all) of the VPC issues before the next release given that instances are now launched in a default VPC by default for new users.

I've already switched from using group-name to instance.group-name filters everywhere given that instance.group-name appears to work for both VPC and non-VPC clusters. I noticed your branch did not update the group-name filter in Cluster.is_cluster_terminated which may be related to why the resource is busy when StarCluster tries to delete the security group. I've updated Cluster.is_cluster_terminated in the develop branch and we're currently testing this change for #270 which is identical to your issue of deleting security groups with VPC. 

Could you try pulling in this change and see if you still have the same problem terminating clusters? @syoyo just tried and is still having the same issue even with instance.group-name used in Cluster.is_cluster_terminated and I'm curious if you're still having the same issue as well.

Thanks again!!

**Comment by adgaudio** [comment]
Hi @jtriley, thanks for your notes!  I just rebased my branch with your
latest changes, I also get @soyo's error when attempting to terminate a vpc
cluster:

> > > Removing sc-testingvpc security group
> > > !!! ERROR - Failed to load cluster settings!
> > > !!! ERROR - Use -f to forcefully terminate the cluster
> > > !!! ERROR - DependencyViolation: resource sg-XXXXXXXX has a dependent object
> > > Traceback (most recent call last):
> > >   [ ... ]
> > >   File "...site-packages/boto/ec2/connection.py", line 2319, in
> > > delete_security_group
> > >     return self.get_status('DeleteSecurityGroup', params, verb='POST')
> > >   File "...site-packages/boto/connection.py", line 1088, in get_status
> > >     raise self.ResponseError(response.status, response.reason, body)
> > > EC2ResponseError: EC2ResponseError: 400 Bad Request

Thanks for looking into this!
Alex

**Comment by jtriley** [comment]
@adgaudio OK good to know, thanks for testing! I'm merging a patch now that should fix the issue.

**Comment by jtriley** [comment]
@adgaudio The fix is in. Test it out and let me know if you still have issues terminating. Thanks!

**Comment by adgaudio** [comment]
It worked for me, too!  Thanks for the fix :)  If there's anything else I
can do to help get this branch into develop, let me know.

We may want to be careful about merging it, because the security groups had
to be renamed from @sc-XXX to sc-XXX because, last I checked (couple months
ago), VPC security groups couldn't start with an '@' symbol.

 If we merged this pr, people's existing security groups wouldn't be
recognized in starcluster., we may want to make "starcluster listclusters"
support naming conventions.   Do you have any insights/plans here?

Alex

**Comment by jph98** [comment]
Hi all,

Is there a date for merging the VPC support back into the trunk at some point this year?  We're interested in using VPC with Starcluster.

Many thanks,
Jon .

**Comment by rayrayson** [comment]
I bugged Justin @ MIT earlier this week and asked him the same question, and he said that SC works in a "default VPC", and also in a VPC if the node that runs StarCluster can access the slave nodes & AWS.

He will update the doc so that everyone can just follow the guide to run SC in VPCs.

**Comment by jtriley** [comment]
@jph98 @rayrayson StarCluster 0.95 has been released with VPC support. Please see the full change log for details:

http://star.mit.edu/cluster/docs/latest/changelog.html#version-0-95
