### ISSUE TITLE
issues with scientific linux ami

### ISSUE THREAD

**Issue by applebird** [jtriley/StarCluster#225]
Hi, I'm trying to use starcluster to lauch the SL ami with two issues,
1. when starcluster is attaching EBS volume, it's using /dev/sdz and can't mount, inside SL, it's a  different device name, is there a quick way to customize device name?
2. the SL image doesn't delete its root EBS volume upon termination. I saved the ami to a new one where root EBS will be deleted upon termination. When I use Amazon web interface to start/terminate the new ami, it works fine, however when use starcluster, the root EBS is still there after termination.

overall it's great, the two issues doesn't exist in Ubuntu ami. however all servers I'm working in are Scientific Linux's so have to make it work... thx!

**Comment by jtriley** [comment]
@applebird My apologies for the delay. Couple questions:
1. You mentioned it shows up as a different device - what's that device?
2. What is the AMI id you're using? I'll test the AMI myself and see what the issue is with root volume termination and StarCluster. The default StarCluster images are all configured to delete the root volume and they're deleted when StarCluster terminates them so something may be up with the AMI block device map configuration.
