### ISSUE TITLE
Are the python package version requirements correct?

### ISSUE THREAD

**Issue by opoplawski** [jtriley/StarCluster#245]
In current git, StarCluster specifies the following requirements:

```
paramiko>=1.10.0
boto>=2.8.0
workerpool>=0.9.2
Jinja2>=2.6
decorator>=3.4.0
pyasn1>=0.1.6
```

Are these version requirements truly accurate?  I'm looking at package for Fedora and EPEL.  In Fedora Rawhide we only have boto 2.6.0.

I'd also like to try to get it working on RHEL6 where we have:

```
paramiko 1.7.5
boto 2.5
workerpool 0.9.2
jinja2 2.2
decorator 3.0.1
pyasn1 0.0.12a
```

Any chance of that?

**Comment by jtriley** [comment]
@opoplawski I tend to keep up with latest paramiko/boto because they often have bug fixes that are valuable and in general I prefer folks to use the latest versions of the deps when easy_install'ing. With that said those versions of the deps should work in theory but you will need to patch setup.py and downgrade the requirements. Is that an issue for you on the RHEL6 packaging side?

**Comment by opoplawski** [comment]
Yeah, I can patch things to use the versions in EL6 - hopefully it will work okay.
