### ISSUE TITLE
No snapshot found for certain AMIs

### ISSUE THREAD

**Issue by realoptimal** [jtriley/StarCluster#330]
When trying to run:
starcluster start -o -s 1 -i m1.large -n ami-765b3e1f newimage

am getting:
!!! ERROR - InvalidSnapshot.NotFound: The snapshot 'snap-ef2791a9' does not exist.

Seems the snapshot backing this ami has been deleted.

**Comment by jtriley** [comment]
Not sure what's going on here - I haven't touched the AMIs and the snapshot does exist in the official StarCluster account. I'll have to ping AWS on this one /cc @schmutze

**Comment by jtriley** [comment]
So I can launch the AMI from the account that owns the snapshot but not on my other accounts. I tried flipping the AMI from public to private and back to public again but it didn't fix the issue.

@schmutze Any ideas?

**Comment by alemagnani** [comment]
I run into the same problem. Is there a workaround at this point? we cannot create clusters anymore

**Comment by jtriley** [comment]
@alemagnani You can use a different AMI (see `starcluster listpublic`) or change regions. If I can't get this resolved in the next day or so I'll simply have to destroy the AMI and recreate it with a new id which sucks but not sure what else to do.

**Comment by jtriley** [comment]
OK seems like this is an issue for _any_ AMI now that I've tested the other AMIs. This is even an issue with the current stable 0.94.2 which was not the case when it was released so I'm fairly certain something changed on Amazon's side. Perhaps the recent RunInstances IAM features? I'll keep you posted.

**Comment by ettorerizzo** [comment]
Hi everyone. I'm facing a similar problem:
"!!! ERROR - InvalidSnapshot.NotFound: The snapshot 'snap-655aed23' does not exist."
However if I run StarCluster with a different AWS account it don't have this error and everything works fine. 
It happens just from one account.

**Comment by jtriley** [comment]
@ettorerizzo Hmmm OK that's good to know. Do you know what type of accounts you have (ie vpc-only, ec2-classic, or both)? I found how to get around this and will push a patch in a moment but I'm still curious what changed - seems like this AMI was working fine for folks with 0.94.2 which obviously hasn't had any changes since it was released (10/21)....

**Comment by jtriley** [comment]
The underlying issue is the fact that StarCluster sets a custom block device mapping for each instance and sets delete_on_termination=True on the root drive (ie the AMI's snapshot). If I remove that piece of code it avoids this issue because the root drive is not specified in the custom block device mapping and simply inherits the root drive settings from the AMI's block device map.

At this point I'm wondering if you no longer can specify the root drive in a custom block device map if you dont own the snapshot or if that's the way it's always been? I think not otherwise I'd imagine hearing complaints about this long ago...

**Comment by alemagnani** [comment]
I tried to create an instance with the ami-765b3e1f from the AMAZON console and it worked fine.

**Comment by ettorerizzo** [comment]
@jtriley Both my account are ec2-classic but I don't have all the permission on the account that doesn't work.
I tried as well to launch the same instance both from aws cli and console and I didn't get any problem.

**Comment by jtriley** [comment]
@alemagnani Yep, as I mentioned it's due to the fact that StarCluster sets delete_on_termation=True on the root volume by default using a custom block device mapping which apparently doesn't work anymore unless you own the AMI/snapshot. I'm putting out a patch release for this given that it's a complete show-stopper for folks, however, I don't believe this was always the case given that users at one point in time were able to launch clusters with 0.94.2 and suddenly can't now.

**Comment by alemagnani** [comment]
when will the patch release be available? thanks

**Comment by jtriley** [comment]
@alemagnani Working on it now. I'll send out the usual announcements and close this bug when it's released.

**Comment by realoptimal** [comment]
Thanks for looking into this and resolving it.  It'd be great to get some AMI's available with more recent versions of hadoop.  Perhaps this community could start publishing some more.
