### ISSUE TITLE
spothistory reports only ec2 classic prices in VPC enabled accounts

### ISSUE THREAD

**Issue by johnbot1** [jtriley/StarCluster#343]
Running spothistory in accounts that are VPC or Classic and VPC enabled will only report prices of classic EC2 instances which can sometimes be wildly different. For example running starcluster spothistory -z us-west-2b -d 1 cc2.8xlarge is the equivalent of going to EC2 > Spot Request > Pricing History and selecting Product: Linux/UNIX Instance:cc2.8xlarge Zone: us-west-2b 

However going to EC2 > Spot Request > Pricing History and selecting Product: Linux/UNIX(Amazon VPC)  Instance:cc2.8xlarge Zone: us-west-2b reports the VPC price which at the time was $7.50 cheaper per hour than the standard non-vpc spot price. It would be great to have a switch in the spothistory price to tell it to either look at the equivalent of Product:Linux/UNIX or Product:Linux/UNIX(Amazon VPC) in the console.

**Comment by jtriley** [comment]
@johnbot1 Good call. I'm updating the code to decide the default spot prices to show based on whether or not you have a default VPC. If you have a default VPC then VPC prices will be your default otherwise it's EC2 classic. I'm also adding `--classic` and `--vpc` options to the `spothistory` command so folks can choose the platform themselves. This is useful, for example, for folks that have both classic and VPC but no default VPC - in this case they can launch instances using either platform but by default classic prices will be shown unless they use the `--vpc` option.
