### ISSUE TITLE
cluster_user's home

### ISSUE THREAD

**Issue by delagoya** [jtriley/StarCluster#41]
Feature Request:  configure the cluster_user's home on the ephemeral storage drive or an EBS volume

**Comment by jtriley** [comment]
You can already configure the cluster_user's home on an EBS volume simply by setting an EBS volume's mount_path to /home:

```
[vol myvol]
volume_id = vol-blahblah
mount_path = /home

[cluster smallcluster]
...
volumes = myvol
```

I'll consider using the ephemeral storage for /home. The benefit is a larger /home directory but we need to think about what the potential drawbacks of this might be if any.

**Comment by delagoya** [comment]
Good point about home on EBS, I didn't think about that one.

The home on root volume suffers from the same drawback as home on ephemeral, since the users will likely not configure snapshots of the OS EBS. It will go away once the master terminates. 

One more issue that Deepak from AWS raised when I mentioned this on the twitter was that it is possible that an EBS instances do not have ephemeral storage, so what to do then?

**Comment by jtriley** [comment]
Right, another issue is that ephemeral storage does not survive a stop/start cycle which would be tricky to communicate effectively to users. The more I think about this, since all you're going for anyway is disk space why not just use the scratch directory (/scratch/cluster_user) which is symlinked to /mnt/cluster_user on startup? This is _usually_ where ephemeral storage is mounted. If that isn't convenient enough users could also configure a symlink to /scratch/cluster_user in their $HOME directories via a simple StarCluster plugin. This would be a useful plugin to have in the StarClusterPlugins project:

https://github.com/jtriley/StarClusterPluginshttps://github.com/jtriley/StarClusterPlugins

**Comment by delagoya** [comment]
Didn't realize there was already a scratch user dir. 

Agreed that this is plugin domain. I'm going to close this issue and investigate plugins.
