### ISSUE TITLE
ebsimage: unmount every non root volume before creating new AMI ?

### ISSUE THREAD

**Issue by srooks10** [jtriley/StarCluster#45]
When using starcluster ebsimage on an EBS AMI (an Ubuntu 11.04 HVM AMI) with a mounted EBS backed volume, the mounted volume is also snapshot during the process. Furthermore when using the newly created AMI the EBS backed volume can not be mounted because the mount point is already in use.
(sorry for the lack of details, I am writing from memory)

workaround: temporarily remove the line beginning with  'VOLUMES= ' in the cluster definition in the ~/.starcluster/config file before launching an instance to be used to create a new AMI.

suggestion: ebsimage should unmount every mounted non root volume before creating the new AMI image.

**Comment by jtriley** [comment]
Ultimately you're right but this is a tricky one because it's not always easy to cleanly unmount a device especially if it's currently in-use and NFS-shared. The ideal situation is not to use volumes in the first place when launching an _image host_ as you've mentioned. I'll have to think about how to handle this best. Perhaps ebsimage just warns or errors out when devices are attached and we add a new command detachvol that tries its best to unshare/detach the volume from the cluster. I'm planning on adding an attachvol command that attaches and NFS-shares volumes anyway so it'd be nice to have the opposite command as well...

**Comment by jtriley** [comment]
I think the new "Customizing the StarCluster AMI" docs will help a lot with this:

https://github.com/jtriley/StarCluster/blob/develop/docs/sphinx/manual/create_new_ami.rst

It describes how to simply create the images host and nothing else (e.g. attaching vols, configuring NFS, etc) which is what you want when you're creating a new AMI.
