### ISSUE TITLE
Long delay while waiting for spot requests to become active

### ISSUE THREAD

**Issue by mcianfrocco** [jtriley/StarCluster#527]
Hello,

I've been using StarCluster over the past 6 months, and recently I've noticed long delays in booting up a StarCluster of spot instances. Normally, a cluster of 6 - 10 instances would boot up within 10 minutes, but now it has been routinely taking longer than an hour (if it even boots up at all). 

A few points: 
-I know that I'm bidding way above the current price
-I can start up a single spot instance at the same bid price through the console within minutes
-If I boot up a StarCluster using on-demand instances, the StarCluster comes online within minutes.

Do anyone know if something has changed within Amazon EC2 to alter the speed at which StarClusters are booted up? 

Thanks for your help,
Mike

StarCluster version 0.95.6
Region: N. Virginia

**Comment by FinchPowers** [comment]
The spot market is really going roller coaster since 3 weeks for some instance types. So it may be the cause. Pay attention to the spot instance requests and see how they move from "pending-evaluation" to "fulfilled".

The "issue" with the current version of StarCluster is that it awaits for the whole set of nodes to be up before configuring them. Check this PR https://github.com/jtriley/StarCluster/pull/463 which "streams" the node addition process.
