### ISSUE TITLE
Load balancer slot calculations

### ISSUE THREAD

**Issue by dmachi** [jtriley/StarCluster#69]
The calculations for the # of slots available is based on the number of cpus on a node instead of getting slots from sge.  This makes the cluster thing there are more slots than actually exist (or can anyway), and doesn't spawn new nodes accordingly.  Additionally, the node addition check looks to see if the #of queued jobs > total number of slots.  This should be #slots requested by the queued jobs > total number of slots, or perhaps even avoid this check altogether.

Avoiding the check, means that whether it would like to add a node is based purely on how long jobs have been queued and not whether slots are available.  The available slots and slots per node are useful for determining how many nodes to add though, so the data is still useful in that context.

**Comment by FinchPowers** [comment]
I have a fix for it https://github.com/datacratic/StarCluster/commit/b938518bc89d58feda6e21e673307b8dc2ce18a3
I'll clean it and put it in a separate branch to allow it to be easily merged.

For it to work, nodes names must be in default format (node###) otherwise it will fail to count the slots. Is it an issue?
