### ISSUE TITLE
Unneeded line in cli.py #278

### ISSUE THREAD

**Issue by godber** [jtriley/StarCluster#7]
I think line 278 of cli.py is unused.

http://github.com/jtriley/StarCluster/blob/master/starcluster/cli.py#L278

Austin

**Comment by jtriley** [comment]
refactor use of inst.stop/terminate for boto2.0a2

add shutdown/terminate methods to node.Node class. in boto-2.0a2
instance.stop() now just puts EBS-backed instances into a 'stopped' state
rather than terminating an instance. 'terminate' has been moved to terminate
method in boto. added shutdown method to node.Node class that will 'stop' in the case
of EBS-backed instances and 'terminate' in the case of instance-storage instances.

remove unnecessary line from CmdStop

closed by 1aff8e9dc757d7d429756d400a5b788e131c482a
