### ISSUE TITLE
SGEPlugin Branch Review

### ISSUE THREAD

**Issue by dmachi** [jtriley/StarCluster#71]
This isn't so much a ticket as it is documentation/message passing.  Via IRC, jtriley and I discussed the SGEplugin branch  and he asked for a peer review/test of that code.  There is no actual work to be done here unless this ticket is converted into "merge SGEPlugin branch into develop/master branches" 

I've done a review and testing of the SGEPlugin branch.  It is working well for me, not withstanding the other issues mention in the issue tracker already.  I haven't made any changes in my branch yet for merging, but the requested peer review of this plugin branch has been taken care.   In this same branch, I'm planning to add in some configurability to the plugin (disable/enable master as an exec host,  and external submission hosts at least) and will submit a pull request when done.  

On a side note,  I think/hope that the disable_queue option can ultimately go away, and simply allow people to add sge as one of their chosen plugins.  While we could also do disable_queue=true/false and  default_queue=sge (or whatever), to me this just adds baggage.  plugins=sge  is just as easy, clear on intent, and easier to control when it is configured and executed in a node's lifecycle.  All that said, I understand that including the plugin as part of the default clustersetup  and disabling/enabling with disable_queue is needed for now for minor version backward compatibility.  But for the next major revision, I'm +1 to making sge (or any queuing system) a plugin rather than being elevated to part of the default.

**Comment by jtriley** [comment]
Just for the record the sge-plugin branch has been merged and will be released in 0.93.2. That'd be great if you could branch from develop and start adding additional functionality to the new SGE plugin to customize the SGE install as mentioned in other issues. I agree that disable_queue should eventually go away and I think it's getting close to being ready we just need to ease users into it given that SGE has been a default since the beginning.

**Comment by jtriley** [comment]
The SGE plugin has been merged.
